### ISSUE TITLE
render pipeline not compatible with pass

### ISSUE THREAD

**Issue by aentity** [hecrj/iced#203]
From iced e680fd27e754aead4003cae72f401090662851b2

When I try integrating into existing project, I get this runtime error:

```
thread 'main' panicked at 'The render pipeline is not compatible with the pass!', .cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:604:5
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::begin_panic
   7: wgpu_native::command::render::render_pass_set_pipeline
             at .cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:604
   8: wgpu_render_pass_set_pipeline
             at .cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:704
   9: wgpu::RenderPass::set_pipeline
             at .cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1170
  10: iced_wgpu::quad::Pipeline::draw
  11: <wgpu_glyph::pipeline::Instance as core::clone::Clone>::clone
  12: iced_wgpu::renderer::Renderer::draw
             at .cargo/git/checkouts/iced-9e73d2fbe1fce35a/e680fd2/wgpu/src/renderer.rs:102
  13: iced_pipeline::IcedPipeline::render
             at iced_pipeline.rs:193
```

Iced pipeline is just basic integration example put into project.

```rust
impl IcedPipeline {
    pub fn init(
        window: &crate::window::Window,
        device: &mut wgpu::Device,
    ) -> Self {
        let cache = Some(Cache::default());
        let renderer = Renderer::new(device, Settings::default());
        let output = (Primitive::None, MouseCursor::OutOfBounds);
        let clipboard = Clipboard::new(&window);
        IcedPipeline {
            cache,
            renderer,
            output,
            clipboard,
            controls: Controls::new(),
            events: Vec::new(),
            color: 0.5,
        }
    }

    pub fn update(
        &mut self,
        window: &crate::window::Window,
        event: crate::window::WindowEvent,
        modifiers: crate::window::ModifiersState,
    ) {
        if let Some(event) =
            iced_winit::conversion::window_event(event, window.scale_factor(), modifiers)
        {
            self.events.push(event);
        }
    }

    pub fn render(
        &mut self,
        device: &mut wgpu::Device,
        encoder: &mut wgpu::CommandEncoder,
        view: &wgpu::TextureView,
        viewport_dimensions: Point2<u32>,
        window: &crate::window::Window,
    ) {
        if self.events.is_empty() {
            return;
        }
        let size = Size::new(800.0, 600.0);
        let mut user_interface = UserInterface::build(
            self.controls.view(self.color),
            size,
            self.cache.take().unwrap(),
            &mut self.renderer,
        );

        let messages = user_interface.update(
            self.events.drain(..),
            self.clipboard.as_ref().map(|c| c as _),
            &self.renderer,
        );

        let user_interface = if messages.is_empty() {
            user_interface
        } else {
            self.cache = Some(user_interface.into_cache());
            for message in messages {
                self.controls.update(message, &mut self.color);
            }
            UserInterface::build(
                self.controls.view(self.color),
                size,
                self.cache.take().unwrap(),
                &mut self.renderer,
            )
        };
        self.output = user_interface.draw(&mut self.renderer);
        self.cache = Some(user_interface.into_cache());
        // CRASH incompatible here
        let _mouse_cursor = self.renderer.draw(
            device,
            encoder,
            Target {
                texture: view,
                viewport: &Viewport::new(viewport_dimensions.x, viewport_dimensions.y),
            },
            &self.output,
            window.scale_factor(),
            &["Some debug information!"],
        );
    }
}
```

render placement is after some other rpasses (similar to imgui):

```rust
{
    let mut rpass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
        color_attachments: &[wgpu::RenderPassColorAttachmentDescriptor {
            attachment: &frame.view,
            resolve_target: None,
            load_op: wgpu::LoadOp::Load,
            store_op: wgpu::StoreOp::Store,
            clear_color: wgpu::Color {
                r: 0.1,
                g: 0.2,
                b: 0.3,
                a: 1.0,
            },
        }],
        depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachmentDescriptor {
            attachment: &depth_buffer,
            depth_load_op: wgpu::LoadOp::Clear,
            depth_store_op: wgpu::StoreOp::Store,
            stencil_load_op: wgpu::LoadOp::Clear,
            stencil_store_op: wgpu::StoreOp::Store,
            clear_depth: 1.0,
            clear_stencil: 0,
        }),
    });
    self.lines.draw(&mut rpass);
}

// CRASH HERE
self.iced.render(
    &mut self.device,
    &mut encoder,
    &frame.view,
    view_port_dimensions,
    &self.window,
);

// for example, imgui here, no render pipeline not compatible with pass issues
```

**Comment by aentity** [comment]
Ah, it looks like iced likes to be in control of swapchain format. I change to:

```
format: wgpu::TextureFormat::Bgra8UnormSrgb,
// was format: wgpu::TextureFormat::Bgra8Unorm,
```

for my swapchain, to match iced, and it renders (except for another incompatible failure in a separate text pipeline i have, i comment for now).

is there good reason for iced to have swapchain requirements and control? (i don't know, just wondering, if should adapt app to use iced swapchain constructor?)

**Comment by hecrj** [comment]
> is there good reason for iced to have swapchain requirements and control?

Not really. It's probably a good idea to allow users to provide their desired format when creating a `Renderer` as part of the `Settings`.

I've been meaning to do this for a while. I will try to quickly add it tomorrow.

**Comment by hecrj** [comment]
@aentity I have opened #205 which should allow you to specify your desired output format in `iced_wgpu::Settings`. Let me know if it works for you.
