### ISSUE TITLE
App runs fine on PC, but not on Laptop

### ISSUE THREAD

**Issue by MGlolenstine** [hecrj/iced#218]
Both times the program was run using `cargo run`, on PC runs without problems, on my Laptop it `panic`s.

Both machines are running Arch Linux.

![image](https://user-images.githubusercontent.com/9406770/76468383-1f7def00-63ec-11ea-9fa0-99d49d96a84a.png)

<details>
<summary>RUST_BACKTRACE=1</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::panicking::panic
             at src/libcore/panicking.rs:51
  14: core::option::Option<T>::unwrap
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15
  15: wgpu_request_adapter
             at /home/notyours/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  16: wgpu::Adapter::request
             at /home/notyours/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  17: <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new
             at /home/notyours/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/5a91b52/wgpu/src/window/backend.rs:21
  18: iced_winit::application::Application::run
             at /home/notyours/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/5a91b52/winit/src/application.rs:166
  19: iced::application::Application::run
             at /home/notyours/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/5a91b52/src/application.rs:177
  20: iced::sandbox::Sandbox::run
             at /home/notyours/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/5a91b52/src/sandbox.rs:128
  21: open2internet::main
             at src/main.rs:13
  22: std::rt::lang_start::{{closure}}
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  26: std::panicking::try
             at src/libstd/panicking.rs:270
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  29: std::rt::lang_start
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  30: main
  31: __libc_start_main
  32: _start
```
</details>

<details>
<summary>RUST_BACKTRACE=full</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0:     0x559419e60684 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x559419e60684 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x559419e60684 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x559419e60684 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x559419e83b2c - core::fmt::write::h393d55821fa8e2cb
                               at src/libcore/fmt/mod.rs:1025
   5:     0x559419e5af37 - std::io::Write::write_fmt::hc6645302c23e4504
                               at src/libstd/io/mod.rs:1426
   6:     0x559419e6281e - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x559419e6281e - std::sys_common::backtrace::print::hc2635fd6c7743ade
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x559419e6281e - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
                               at src/libstd/panicking.rs:193
   9:     0x559419e62511 - std::panicking::default_hook::h66e3afff11b02e47
                               at src/libstd/panicking.rs:210
  10:     0x559419e62efb - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
                               at src/libstd/panicking.rs:471
  11:     0x559419e62aae - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x559419e7f80e - core::panicking::panic_fmt::he794217b0df3f806
                               at src/libcore/panicking.rs:84
  13:     0x559419e7f75a - core::panicking::panic::h104b3bcaeb5f1ff0
                               at src/libcore/panicking.rs:51
  14:     0x5594199c023c - core::option::Option<T>::unwrap::h9b7d9ad3c60a0172
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15
  15:     0x559419af605a - wgpu_request_adapter
                               at /home/notyours/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  16:     0x55941990b5fe - wgpu::Adapter::request::hdd8c5f292c552827
                               at /home/notyours/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  17:     0x55941986c921 - <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new::hde198c6179f9b1cf
                               at /home/notyours/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/5a91b52/wgpu/src/window/backend.rs:21
  18:     0x5594193a034d - iced_winit::application::Application::run::hf3bcce1a6c6e8710
                               at /home/notyours/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/5a91b52/winit/src/application.rs:166
  19:     0x5594193d53c4 - iced::application::Application::run::hd1666a2fa3dbf015
                               at /home/notyours/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/5a91b52/src/application.rs:177
  20:     0x5594193d55b1 - iced::sandbox::Sandbox::run::h1a0abf7afa948d31
                               at /home/notyours/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/5a91b52/src/sandbox.rs:128
  21:     0x559419392415 - open2internet::main::hb237b82e5c452c60
                               at src/main.rs:13
  22:     0x55941938e570 - std::rt::lang_start::{{closure}}::h251cbdff5e2b54ed
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  23:     0x559419e62943 - std::rt::lang_start_internal::{{closure}}::h4aedff5d9863b36b
                               at src/libstd/rt.rs:52
  24:     0x559419e62943 - std::panicking::try::do_call::h0630fe3da32a089b
                               at src/libstd/panicking.rs:292
  25:     0x559419e67afa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  26:     0x559419e63450 - std::panicking::try::hdfbe2fd873ac646c
                               at src/libstd/panicking.rs:270
  27:     0x559419e63450 - std::panic::catch_unwind::hd7a9c10fa2bee1bc
                               at src/libstd/panic.rs:394
  28:     0x559419e63450 - std::rt::lang_start_internal::hb8081e0e7e42ac0d
                               at src/libstd/rt.rs:51
  29:     0x55941938e549 - std::rt::lang_start::hb4f916775cf60134
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  30:     0x55941939244a - main
  31:     0x7f1b87809023 - __libc_start_main
  32:     0x55941934f19e - _start
  33:                0x0 - <unknown>
```

</details>

**Comment by hecrj** [comment]
See #194.

This is related to a graphics driver issue. We only support modern graphics backends for now: Vulkan, Metal, and DirectX 12/11.

**Comment by MGlolenstine** [comment]
My Laptop had corrupted drivers, which only affected OpenGL and Vulkan renderers, so it got solved with an update.

Thanks for pointing it out!
