### ISSUE TITLE
Unable to run tour on Linux/Wayland without XWayland

### ISSUE THREAD

**Issue by sklv** [hecrj/iced#255]
Hi,

This is a cool project!

I'm running sway on gentoo without XWayland. Happy to supply any diagnostic information and try stuff.

I wasn't able to run `cargo run --package tour` with this stacktrace:

```
$ RUST_BACKTRACE=full cargo run --package todos
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/todos`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0:     0x5655561560a3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he791667536cc6636
   1:     0x5655561704ad - core::fmt::write::h9812d54d3d1b3ed1
   2:     0x565556154885 - std::io::Write::write_fmt::haf77cbecd15fd6f5
   3:     0x56555615946e - std::panicking::default_hook::{{closure}}::h3e9084c18932584e
   4:     0x565556159180 - std::panicking::default_hook::hd9ee49f6927eb94c
   5:     0x565556159b4b - std::panicking::rust_panic_with_hook::h6f1a44b2613a334b
   6:     0x5655561596fe - rust_begin_unwind
   7:     0x56555617585e - core::panicking::panic_fmt::hc8975cca6005847b
   8:     0x5655561757aa - core::panicking::panic::he3656d1829bb319f
   9:     0x56555595237c - core::option::Option<T>::unwrap::hfd09256a4fa43409
                               at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libcore/macros/mod.rs:15
  10:     0x565555a878fa - wgpu_request_adapter
                               at /home/sklv/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  11:     0x56555589ce9e - wgpu::Adapter::request::h0ba42cc666fff90a
                               at /home/sklv/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  12:     0x5655558606b1 - <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new::hb31f2df51b101cbc
                               at wgpu/src/window/backend.rs:21
  13:     0x56555572df59 - iced_winit::application::Application::run::he009226fc0437926
                               at /home/sklv/code/iced/winit/src/application.rs:180
  14:     0x5655556d6927 - iced::application::Application::run::hc5da71fb83a0f2ff
                               at /home/sklv/code/iced/src/application.rs:201
  15:     0x565555700b68 - todos::main::h3c56e7b7416c2d20
                               at examples/todos/src/main.rs:9
  16:     0x5655556b3ad0 - std::rt::lang_start::{{closure}}::h6aba34015c75fe9d
                               at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libstd/rt.rs:67
  17:     0x565556159593 - std::panicking::try::do_call::hbff5af65fcac42c3
  18:     0x56555615aa1a - __rust_maybe_catch_panic
  19:     0x56555614b72c - std::rt::lang_start_internal::h31d7321f9a231a49
  20:     0x5655556b3aa9 - std::rt::lang_start::h1d35fc8277d2a3be
                               at /var/tmp/portage/dev-lang/rust-1.41.1/work/rustc-1.41.1-src/src/libstd/rt.rs:67
  21:     0x565555704b8a - main
  22:     0x7efbff390eab - __libc_start_main
  23:     0x56555564f1da - _start
  24:                0x0 - <unknown>
```

It looks like it's failing to get an adapter.

Not sure how to troubleshoot further.

**Comment by selfup** [comment]
Yea same here. Both master and stable (0.1)

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by TimotheeGerber** [comment]
Hi,

I had a similar issue on Archlinux. I installed `vulkan-icd-loader` and `vulkan-intel` (because I have an Intel iGPU) to solve the issue. I don't know the equivalent for Gentoo, but I suggest that you check that Vulkan is installed on your system.

[Vulkan installation (Archlinux documentation)](https://wiki.archlinux.org/index.php/Vulkan#Installation) may help.

Have a nice day!

**Comment by sklv** [comment]
Thanks for the quick response!

I fully resolved my issue by:
1. Add `vulkan` to the list of global use flags in `make.conf`.
2. Rebuild packages with the new flag (just `mesa`).
3. Install `media-libs/vulkan-loader`.

After that, the demo ran fine.
