### ISSUE TITLE
Error running tour with Ubuntu and i3wm

### ISSUE THREAD

**Issue by augustobmoura** [hecrj/iced#263]
Running `cargo run --package tour` gives:
```
     Running `target/debug/tour`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/augustomoura/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
```
With backtrace:
```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: core::option::Option<T>::unwrap
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/macros/mod.rs:10
  15: wgpu_request_adapter
             at /home/augustomoura/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  16: wgpu::Adapter::request
             at /home/augustomoura/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  17: <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new
             at wgpu/src/window/backend.rs:21
  18: iced_winit::application::Application::run
             at ./winit/src/application.rs:180
  19: iced::application::Application::run
             at ./src/application.rs:201
  20: iced::sandbox::Sandbox::run
             at ./src/sandbox.rs:139
  21: tour::main
             at examples/tour/src/main.rs:10
  22: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  26: std::panicking::try
             at src/libstd/panicking.rs:281
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  29: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  30: main
  31: __libc_start_main
  32: _start
```

**Comment by hecrj** [comment]
This issue is caused by wgpu not being able to find a suitable graphics adapter. A similar issue is #194.

Could you try installing Vulkan graphics drivers?

**Comment by augustobmoura** [comment]
My computer doesn't have a dedicated card for video, and I'm having difficulties to install vulkan for the Intel chipset, any tips on doing itt?

**Comment by augustobmoura** [comment]
So, I get the drivers and it worked perfectly. Keep the awesome job!
