### ISSUE TITLE
Tour failed to run on xmonad

### ISSUE THREAD

**Issue by SchrodingerZhu** [hecrj/iced#277]
## backtrace
```
iced/examples on 🌱 master via 💻mem 23%
🕙[ 14:05:56 ] λ env RUST_BACKTRACE=full cargo run --package tour
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `/home/schrodinger/Documents/code/iced/target/debug/tour`
[2020-04-08T06:05:59Z ERROR gfx_backend_vulkan]
    GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 94654141621488)

[2020-04-08T06:05:59Z ERROR gfx_backend_vulkan]
    GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 94654141621488)

[2020-04-08T06:05:59Z ERROR gfx_backend_vulkan]
    GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 94654141621488)

[2020-04-08T06:05:59Z ERROR gfx_backend_vulkan]
    GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 94654141621488)

[2020-04-08T06:05:59Z ERROR gfx_backend_vulkan] Could not enumerate physical devices! Initialization of a object has failed
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/schrodinger/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
stack backtrace:
   0:     0x56166015d5f4 - backtrace::backtrace::libunwind::trace::h1b09fc4a9b690655
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x56166015d5f4 - backtrace::backtrace::trace_unsynchronized::h344cfe7eff25c17f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x56166015d5f4 - std::sys_common::backtrace::_print_fmt::hf4c3cd41415080d9
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x56166015d5f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd8dc9b9566855c21
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x56166018527c - core::fmt::write::h322ed88f0d541bed
                               at src/libcore/fmt/mod.rs:1069
   5:     0x56166015a433 - std::io::Write::write_fmt::h4e19d6a4148d361d
                               at src/libstd/io/mod.rs:1439
   6:     0x56166015fe25 - std::sys_common::backtrace::_print::h5cc4d1f6a6f3ace3
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x56166015fe25 - std::sys_common::backtrace::print::hc64d93b271cb3738
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56166015fe25 - std::panicking::default_hook::{{closure}}::h6ea801765a31224f
                               at src/libstd/panicking.rs:198
   9:     0x56166015fb62 - std::panicking::default_hook::he1a04558e6410710
                               at src/libstd/panicking.rs:218
  10:     0x561660160482 - std::panicking::rust_panic_with_hook::h98f1a36d6119a43d
                               at src/libstd/panicking.rs:511
  11:     0x56166016006b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x561660183041 - core::panicking::panic_fmt::hb4a15587d96d3d02
                               at src/libcore/panicking.rs:111
  13:     0x561660182f8d - core::panicking::panic::haded8ecbbf05f17f
                               at src/libcore/panicking.rs:54
  14:     0x56165f9da3e7 - core::option::Option<T>::unwrap::ha77c6d9d09bf959b
                               at /home/schrodinger/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:34
  15:     0x56165fac7d8e - wgpu_request_adapter
                               at /home/schrodinger/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  16:     0x56165f93ef09 - wgpu::Adapter::request::he83f0c8e1b6bc4a4
                               at /home/schrodinger/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  17:     0x56165f664c11 - <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new::haf52e830c698523a
                               at wgpu/src/window/backend.rs:21
  18:     0x56165f322325 - iced_winit::application::Application::run::hd92434c96e341f9b
                               at /home/schrodinger/Documents/code/iced/winit/src/application.rs:180
  19:     0x56165f303275 - iced::application::Application::run::h973bc9ecc2885524
                               at /home/schrodinger/Documents/code/iced/src/application.rs:201
  20:     0x56165f303461 - iced::sandbox::Sandbox::run::h0171824f490af817
                               at /home/schrodinger/Documents/code/iced/src/sandbox.rs:139
  21:     0x56165f36a11e - tour::main::hac979dc58fa88854
                               at examples/tour/src/main.rs:10
  22:     0x56165f39c6eb - std::rt::lang_start::{{closure}}::hcb60786670e18366
                               at /home/schrodinger/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  23:     0x561660160998 - std::rt::lang_start_internal::{{closure}}::h9ae1dfc91ccedf40
                               at src/libstd/rt.rs:52
  24:     0x561660160998 - std::panicking::try::do_call::h8bb36c6d549cca28
                               at src/libstd/panicking.rs:331
  25:     0x561660160998 - std::panicking::try::h9415ab08168fbb75
                               at src/libstd/panicking.rs:274
  26:     0x561660160998 - std::panic::catch_unwind::h8f6f0c0a756eb2de
                               at src/libstd/panic.rs:394
  27:     0x561660160998 - std::rt::lang_start_internal::h65aa7f30d8213694
                               at src/libstd/rt.rs:51
  28:     0x56165f39c6c7 - std::rt::lang_start::hafad0df7b002a555
                               at /home/schrodinger/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  29:     0x56165f37072a - main
  30:     0x7fe8b2a68023 - __libc_start_main
  31:     0x56165f2c41be - _start
  32:                0x0 - <unknown>
```
## Toolchain
```
cargo 1.44.0-nightly (6e07d2dfb 2020-03-31)
```

## OS Info
```
5.6.2-zen1-2-zen #1 ZEN SMP PREEMPT Sun, 05 Apr 2020 05:14:52 +0000 x86_64 GNU/Linux
```

## DM Info
```
🕙[ 13:57:36 ] λ plasmashell --version
plasmashell 5.18.4
iced/examples on 🌱 master via 💻mem 22%
🕙[ 13:57:43 ] λ kded5 --version
kded5 5.68.0   
```

## XMonad (WM) Info
```
xmonad 0.15
```

**Comment by SchrodingerZhu** [comment]
It turns to be a driver issue. I was fooled by some backtraces. Sorry to bother.

**Comment by matthiasbeyer** [comment]
Care to share what fixed your problem?
