### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by justinmoon** [hecrj/iced#284]
```
$ RUST_BACKTRACE=full cargo run --package counter
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/counter`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
stack backtrace:
   0:     0x560854118704 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x560854118704 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x560854118704 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x560854118704 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x560854138bcc - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x560854115917 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x56085411a905 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x56085411a905 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56085411a905 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x56085411a5f1 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x56085411af6a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x56085411ab50 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x560854136a61 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x5608541369ad - core::panicking::panic::hcdc9f0ba8d71d265
                               at src/libcore/panicking.rs:52
  14:     0x56085396ad37 - core::option::Option<T>::unwrap::hce042dfbc1ff19aa
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/macros/mod.rs:10
  15:     0x560853aaa266 - wgpu_request_adapter
                               at /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  16:     0x5608538fe74e - wgpu::Adapter::request::h6dc55b08ffb36bde
                               at /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  17:     0x560853833f01 - <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new::hd0c4ebe110ed2945
                               at wgpu/src/window/backend.rs:21
  18:     0x56085374ce71 - iced_winit::application::Application::run::hef13b9c0f72c1191
                               at /home/justin/dev/iced/winit/src/application.rs:180
  19:     0x56085379e647 - iced::application::Application::run::h1ebca9439a54ea39
                               at /home/justin/dev/iced/src/application.rs:201
  20:     0x56085379e811 - iced::sandbox::Sandbox::run::hd5f9e38d01e4f439
                               at /home/justin/dev/iced/src/sandbox.rs:139
  21:     0x5608537d48c8 - counter::main::h2f03e7b2adf2d880
                               at examples/counter/src/main.rs:4
  22:     0x5608537cc440 - std::rt::lang_start::{{closure}}::h1c8f60ca6472e181
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  23:     0x56085411aa33 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  24:     0x56085411aa33 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  25:     0x56085411ed77 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  26:     0x56085411b4d0 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  27:     0x56085411b4d0 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  28:     0x56085411b4d0 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  29:     0x5608537cc419 - std::rt::lang_start::h2572600627a9280f
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  30:     0x5608537d4d9a - main
  31:     0x7f02dea69023 - __libc_start_main
  32:     0x5608537411ae - _start
  33:                0x0 - <unknown>
```

I'm on Arch Linux:

```
$ uname -srm
Linux 5.5.13-arch2-1 x86_64
```

**Comment by arranf** [comment]
I'm also getting this.

**Comment by hecrj** [comment]
Related to #277, #263, #255, and #256.
