### ISSUE TITLE
Crash when using more than one custom widgets that use Canvas features for rendering

### ISSUE THREAD

**Issue by BillyDM** [hecrj/iced#349]
I am trying to create custom widgets that use the Canvas rendering features of iced. However, it is crashing when I have two or more widgets that render using this feature. It only crashes on debug mode; running with `--release` shows it rendering correctly.

I attached an example that causes this crash.
[iced_stroke_crash.zip](https://github.com/hecrj/iced/files/4645484/iced_stroke_crash.zip)

The output of `env RUST_BACKTRACE=full cargo run`:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `64`,
 right: `0`: Misaligned dynamic buffer offset: 64 does not align with 256', /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:251:13
stack backtrace:
   0:     0x55b46edb94c4 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x55b46edb94c4 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x55b46edb94c4 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55b46edb94c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55b46eddc00c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x55b46edb6663 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:     0x55b46edbbd05 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55b46edbbd05 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55b46edbbd05 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:     0x55b46edbba52 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:     0x55b46edbc362 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:     0x55b46edbbf4b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x55b46edbbebb - std::panicking::begin_panic_fmt::h7c14cf40a8be97ee
                               at src/libstd/panicking.rs:332
  13:     0x55b46e7f24d4 - wgpu_native::command::render::render_pass_set_bind_group::h9df561ef5a26152d
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:251
  14:     0x55b46e7f2a52 - wgpu_render_pass_set_bind_group
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/render.rs:297
  15:     0x55b46e5e9c2e - wgpu::RenderPass::set_bind_group::h01a2de7a6c65fb1a
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1157
  16:     0x55b46e5964da - iced_wgpu::triangle::Pipeline::draw::h219b1ee83175a9d0
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.2/src/triangle.rs:327
  17:     0x55b46e55bff5 - iced_wgpu::renderer::Renderer::flush::hd20eeb865cd78511
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.2/src/renderer.rs:358
  18:     0x55b46e4cdb28 - iced_wgpu::renderer::Renderer::draw::hee34b70b05c12c73
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.2/src/renderer.rs:114
  19:     0x55b46e49a485 - <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::draw::h8414819477e8cf4e
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.2/src/window/backend.rs:97
  20:     0x55b46e49e756 - iced_winit::application::Application::run::{{closure}}::h665596509eee0f77
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.rs:331
  21:     0x55b46e4fc0b3 - winit::platform_impl::platform::sticky_exit_callback::h015bde6614d2d436
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
  22:     0x55b46e4b6887 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h77b2bd376478e000
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:312
  23:     0x55b46e4b791b - winit::platform_impl::platform::x11::EventLoop<T>::run::h1c6d93965899b975
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:390
  24:     0x55b46e4fbe4c - winit::platform_impl::platform::EventLoop<T>::run::h7560f22bb7937768
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:645
  25:     0x55b46e4faea4 - winit::event_loop::EventLoop<T>::run::hb18bd6bf7e9201a2
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  26:     0x55b46e4bad04 - iced_winit::application::Application::run::h284668e780a9be6b
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.rs:214
  27:     0x55b46e46f0e7 - iced::application::Application::run::h99fa56672e3e9edf
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.1/src/application.rs:201
  28:     0x55b46e46f281 - iced::sandbox::Sandbox::run::h4b850fa20e1b778a
                               at /home/billym/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.1/src/sandbox.rs:139
  29:     0x55b46e506098 - iced_stroke_crash::main::h75d879cb5dc3a483
                               at src/main.rs:110
  30:     0x55b46e4fd2db - std::rt::lang_start::{{closure}}::h5d116171458e5b05
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  31:     0x55b46edbbe23 - std::rt::lang_start_internal::{{closure}}::h9a4aa16acf1cdc99
                               at src/libstd/rt.rs:52
  32:     0x55b46edbbe23 - std::panicking::try::do_call::h0b6fc9f6090c1e2b
                               at src/libstd/panicking.rs:303
  33:     0x55b46edc01b7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  34:     0x55b46edbc94c - std::panicking::try::h9eaeeaa81242ec77
                               at src/libstd/panicking.rs:281
  35:     0x55b46edbc94c - std::panic::catch_unwind::h07d504c1b691e8fb
                               at src/libstd/panic.rs:394
  36:     0x55b46edbc94c - std::rt::lang_start_internal::hcea4e704875ab132
                               at src/libstd/rt.rs:51
  37:     0x55b46e4fd2b7 - std::rt::lang_start::h3930cc3841bbba4e
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  38:     0x55b46e50640a - main
  39:     0x7fa37919d023 - __libc_start_main
  40:     0x55b46e4691ae - _start
  41:                0x0 - <unknown>
```

I am running Manjaro Linux with kernel version 5.5.19-1-MANJARO and the Budgie desktop environment. I am using an AMD RX 570 graphics card.

My graphics card info from `lspci -v`
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef) (prog-if 00 [VGA controller])
        Subsystem: XFX Pine Group Inc. Radeon RX 570
        Flags: bus master, fast devsel, latency 0, IRQ 35
        Memory at c0000000 (64-bit, prefetchable) [size=256M]
        Memory at d0000000 (64-bit, prefetchable) [size=2M]
        I/O ports at e000 [size=256]
        Memory at dfe00000 (32-bit, non-prefetchable) [size=256K]
        Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu

01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
        Subsystem: XFX Pine Group Inc. Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
        Flags: bus master, fast devsel, latency 0, IRQ 34
        Memory at dfe60000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
```

**Comment by hecrj** [comment]
I believe this is fixed in `master` by https://github.com/hecrj/iced/commit/f59832e88e9e6c72cd65d51de6fbf91bddf4a9d3.

**Comment by BillyDM** [comment]
When can I expect this fix in the cargo crate? I'm using this in the iced_audio crate I'm working on, and I have iced, iced_native, and iced_wgpu as the dependencies of the crate. Should I set the dependencies to the GitHub version? How would I do that?

**Comment by hecrj** [comment]
> Should I set the dependencies to the GitHub version? How would I do that?

You can change your `Cargo.toml`:

```toml
[dependencies]
iced = { git = "https://github.com/hecrj/iced.git" }
iced_native = { git = "https://github.com/hecrj/iced.git" }
iced_wgpu = { git = "https://github.com/hecrj/iced.git" }
```

But keep in mind you won't be able to release new versions of your crate while you depend on unreleased changes of `iced`.

> When can I expect this fix in the cargo crate?

I can backport the fix. I thought the released version wasn't affected.

**Comment by BillyDM** [comment]
Okay, thanks for your help! I decided to just have a simplified knob style that only uses Quads for now, and I will add the canvas style when the iced crate gets updated.
