### ISSUE TITLE
cargo run --package tour error (debian)

### ISSUE THREAD

**Issue by buxx** [hecrj/iced#357]
Hello,

I fail to run examples too:

```
➜  iced git:(master) ✗ RUST_BACKTRACE=1 cargo run --package tour
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/tour`
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] [loader] setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] [loader] vkEnumeratePhysicalDevices: Failed in dispatch call used to determine number of available GPUs
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] [loader] setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] [loader] setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader.
[2020-05-25T08:01:49Z ERROR gfx_backend_vulkan] Could not enumerate physical devices! Initialization of a object has failed
thread 'main' panicked at 'Request adapter', wgpu/src/window/backend.rs:22:27
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_failed
             at src/libcore/option.rs:1203
  14: core::option::Option<T>::expect
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/option.rs:347
  15: <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new::{{closure}}
             at wgpu/src/window/backend.rs:22
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/future.rs:44
  17: futures_executor::local_pool::block_on::{{closure}}
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  18: futures_executor::local_pool::run_executor::{{closure}}
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/local.rs:262
  20: std::thread::local::LocalKey<T>::with
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/thread/local.rs:239
  21: futures_executor::local_pool::run_executor
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  22: futures_executor::local_pool::block_on
             at /home/bastien/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  23: <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new
             at wgpu/src/window/backend.rs:21
  24: iced_winit::application::Application::run
             at ./winit/src/application.rs:180
  25: iced::application::Application::run
             at ./src/application.rs:201
  26: iced::sandbox::Sandbox::run
             at ./src/sandbox.rs:139
  27: tour::main
             at examples/tour/src/main.rs:10
  28: std::rt::lang_start::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  29: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  30: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  32: std::panicking::try
             at src/libstd/panicking.rs:281
  33: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  34: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  35: std::rt::lang_start
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  36: main
  37: __libc_start_main
  38: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

* Linux PC-Fixe-01 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
* Cedar [Radeon HD 5000/6000/7350/8350 Series]

```
➜  iced git:(master) ✗ sudo find /dev -group video
/dev/fb0
/dev/dri/card0
/dev/dri/renderD128
/dev/dri/controlD64
➜  iced git:(master) ✗ glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: X.Org (0x1002)
OpenGL vendor string: X.Org
```

Something can i do ?

**Comment by buxx** [comment]
Directly related to https://github.com/gfx-rs/wgpu-rs/issues/324

**Comment by hecrj** [comment]
You could try the upcoming OpenGL renderer in #354.

**Comment by buxx** [comment]
Hello @hecrj  !

Using `feature/glow-renderer` branch, it is working ! Nice job. Note, in "tour" example, i can't see image (this is the only bug i can see):

![Sélection_274](https://user-images.githubusercontent.com/1104637/82871103-4e0e5f00-9f31-11ea-991f-69d8b8c92e7b.png)

**Comment by hecrj** [comment]
@buxx Glad it worked!

That's expected, images and SVG are not supported yet in the OpenGL renderer.
