### ISSUE TITLE
Iced sometimes crashes when using trash::remove

### ISSUE THREAD

**Issue by nnt0** [hecrj/iced#374]
Okay, I'm a bit confused with this one.
I've found a problem that causes a crash when calling [trash::remove](https://docs.rs/trash/1.0.1/trash/fn.remove.html).

I've made a minimal example to test it with Application and Sandbox and the behaviour is the same. Altough sometimes it crashes the first time the function is called other times it takes up to 20 times or more.

I'm running this on a Windows 10 machine, I've not tested if this also happens on other operating systems.

Code:
```rust
use iced::{Settings, executor, Command, Element, Button, button, Text};
use iced::Sandbox;
// use iced::Application;

fn main() {
    Demo::run(Settings::default());
}

#[derive(Debug, Clone)]
enum Message {
    ButtonPressed,
}

struct Demo {
    button: button::State,
}

impl Sandbox for Demo {
    type Message = Message;

    fn new() -> Demo {
        Demo { button: button::State::new() }
    }

    fn title(&self) -> String {
        String::from("Test")
    }

    fn update(&mut self, _message: Self::Message) {
        std::fs::File::create("testfile").unwrap();
        trash::remove("testfile").unwrap();
    }

    fn view(&mut self) -> Element<Self::Message> {
        Button::new(&mut self.button, Text::new("Delete File")).on_press(Message::ButtonPressed).into()
    }
}

// impl Application for Demo {
//     type Executor = executor::Null;
//     type Message = Message;
//     type Flags = ();

//     fn new(_: ()) -> (Demo, Command<Self::Message>) {
//         (Demo { button: button::State::new() }, Command::none())
//     }

//     fn title(&self) -> String {
//         String::from("Test")
//     }

//     fn update(&mut self, _message: Self::Message) -> Command<Self::Message> {
        // std::fs::File::create("testfile").unwrap();
        // trash::remove("testfile").unwrap();
//         Command::none()
//     }

//     fn view(&mut self) -> Element<Self::Message> {
//         Button::new(&mut self.button, Text::new("Delete File")).on_press(Message::ButtonPressed).into()
//     }
// }
```

Backtrace and error:

```
thread 'main' panicked at 'assertion failed: flush_paint_messages(None, &subclass_input.event_loop_runner)', <::std::macros::panic macros>:2:4
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\fmt\mod.rs:1063
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:470
  10: std::panicking::begin_panic<str*>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:397
  11: winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<TESTING::Message>
             at <::std::macros::panic macros>:2
  12: std::panic::{{impl}}::call_once<isize,closure-0>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  13: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  14: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  15: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  16: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  17: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<TESTING::Message>::catch_unwind<TESTING::Message,isize,closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  18: winit::platform_impl::platform::event_loop::thread_event_target_callback<TESTING::Message>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:2120
  19: DefSubclassProc
  20: DefSubclassProc
  21: CallWindowProcW
  22: DispatchMessageW
  23: IsWindowVisible
  24: KiUserCallbackDispatcher
  25: NtUserDispatchMessage
  26: DispatchMessageW
  27: Ordinal87
  28: Ordinal87
  29: Ordinal87
  30: CoWaitForMultipleHandles
  31: CoWaitForMultipleHandles
  32: Ordinal87
  33: CoRegisterClassObject
  34: Ordinal86
  35: CStdStubBuffer_Invoke
  36: NdrClientCall3
  37: CoGetApartmentType
  38: ObjectStublessClient32
  39: SHShellFolderView_Message
  40: DllMain
  41: SHFileOperationWithAdditionalFlags
  42: trash::platform::remove_all<[str*; 1]*,str**>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.1\src\windows.rs:60
  43: trash::platform::remove<str*>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.1\src\windows.rs:71
  44: trash::remove<str*>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.1\src\lib.rs:49
  45: TESTING::{{impl}}::update
             at .\src\main.rs:31
  46: iced::sandbox::{{impl}}::update<TESTING::Demo>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-0.1.1\src\sandbox.rs:160
  47: iced::application::{{impl}}::update<TESTING::Demo>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-0.1.1\src\application.rs:242
  48: iced_winit::application::Application::run::{{closure}}::{{closure}}<iced::application::Instance<TESTING::Demo>>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.1.0\src\application.rs:267
  49: iced_futures::executor::Executor::enter<iced_futures::executor::null::Null,iced_futures::command::Command<TESTING::Message>,closure-2>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_futures-0.1.2\src\executor.rs:62
  50: iced_futures::runtime::Runtime<iced_native::hasher::Hasher, iced_native::event::Event, iced_futures::executor::null::Null, iced_winit::proxy::Proxy<TESTING::Message>, TESTING::Message>::enter<iced_native::hasher::Hasher,iced_native::event::Event,iced_futu
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_futures-0.1.2\src\runtime.rs:58
  51: iced_winit::application::Application::run::{{closure}}<iced::application::Instance<TESTING::Demo>>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.1.0\src\application.rs:267
  52: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<TESTING::Message,closure-1>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:200
  53: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<TESTING::Message>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<TESTING::Message>, mut winit::event_loop::ControlFlow*)>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc\boxed.rs:1024
  54: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<TESTING::Message>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:239
  55: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  56: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  57: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  58: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  59: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  60: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<TESTING::Message>::catch_unwind<TESTING::Message,(),closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  61: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<TESTING::Message>::call_event_handler<TESTING::Message>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:233
  62: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<TESTING::Message>::move_state_to<TESTING::Message>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:319
  63: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<TESTING::Message>::main_events_cleared<TESTING::Message>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:225
  64: winit::platform_impl::platform::event_loop::flush_paint_messages<TESTING::Message>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:663
  65: winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<TESTING::Message>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1938
  66: std::panic::{{impl}}::call_once<isize,closure-0>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  67: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  68: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  69: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  70: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  71: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<TESTING::Message>::catch_unwind<TESTING::Message,isize,closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  72: winit::platform_impl::platform::event_loop::thread_event_target_callback<TESTING::Message>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:2120
  73: DefSubclassProc
  74: DefSubclassProc
  75: CallWindowProcW
  76: DispatchMessageW
  77: IsWindowVisible
  78: KiUserCallbackDispatcher
  79: NtUserDispatchMessage
  80: DispatchMessageW
  81: winit::platform_impl::platform::event_loop::EventLoop<TESTING::Message>::run_return<TESTING::Message,closure-1>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:215
  82: winit::platform_impl::platform::event_loop::EventLoop<TESTING::Message>::run<TESTING::Message,closure-1>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:185
  83: winit::event_loop::EventLoop<TESTING::Message>::run<TESTING::Message,closure-1>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\event_loop.rs:149
  84: iced_winit::application::Application::run<iced::application::Instance<TESTING::Demo>>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.1.0\src\application.rs:214
  85: iced::application::Application::run<TESTING::Demo>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-0.1.1\src\application.rs:201
  86: iced::sandbox::Sandbox::run<TESTING::Demo>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-0.1.1\src\sandbox.rs:139
  87: TESTING::main
             at .\src\main.rs:6
  88: std::rt::lang_start::{{closure}}<()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\rt.rs:67
  89: std::rt::lang_start_internal::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\rt.rs:52
  90: std::panicking::try::do_call<closure-0,i32>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:303
  91: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  92: std::panicking::try
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:281
  93: std::panic::catch_unwind
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panic.rs:394
  94: std::rt::lang_start_internal
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\rt.rs:51
  95: std::rt::lang_start<()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\rt.rs:67
  96: main
  97: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  98: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  99: BaseThreadInitThunk
 100: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\TESTING.exe` (exit code: 101)
```

**Comment by hecrj** [comment]
The backtrace seems to tell us `trash` is somehow interacting with `winit`'s event loop.

First, we need to identify the issue. I think `iced` may not be involved here. I'd first try to reproduce the crash only with `winit` and `trash`.

**Comment by nnt0** [comment]
I've tried it again with just winit and it panics again when i call trash::remove. I'm assuming this means I should report this to winit?

```rust
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            }
            if window_id == window.id() => *control_flow = ControlFlow::Exit,
            _ => {
                std::fs::File::create("testfile").unwrap();
                trash::remove("testfile").unwrap();
            }
        }
    });
}
```
```
thread 'main' panicked at 'either event handler is re-entrant (likely), or no event handler is registered (very unlikely)', C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:235:37
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\fmt\mod.rs:1063
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:470
  10: std::panicking::begin_panic_handler
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:378
  11: core::panicking::panic_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\panicking.rs:85
  12: core::option::expect_failed
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\option.rs:1203
  13: core::option::Option<alloc::boxed::Box<FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>>::expect<alloc::boxed::Box<FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\option.rs:347
  14: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:235
  15: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  16: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  18: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  19: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  20: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),(),closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  21: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:233
  22: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::move_state_to<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:319
  23: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::main_events_cleared<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:225
  24: winit::platform_impl::platform::event_loop::flush_paint_messages<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:663
  25: winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1938
  26: std::panic::{{impl}}::call_once<isize,closure-0>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  27: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  28: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  29: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  30: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  31: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),isize,closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  32: winit::platform_impl::platform::event_loop::thread_event_target_callback<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:2120
  33: DefSubclassProc
  34: DefSubclassProc
  35: CallWindowProcW
  36: DispatchMessageW
  37: IsWindowVisible
  38: KiUserCallbackDispatcher
  39: NtUserDispatchMessage
  40: DispatchMessageW
  41: Ordinal87
  42: Ordinal87
  43: Ordinal87
  44: CoWaitForMultipleHandles
  45: CoWaitForMultipleHandles
  46: Ordinal87
  47: CoRegisterClassObject
  48: Ordinal86
  49: CStdStubBuffer_Invoke
  50: NdrClientCall3
  51: CoGetApartmentType
  52: ObjectStublessClient32
  53: SHShellFolderView_Message
  54: DllMain
  55: SHFileOperationWithAdditionalFlags
  56: trash::platform::remove_all<[str*; 1]*,str**>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.1\src\windows.rs:60
  57: trash::platform::remove<str*>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.1\src\windows.rs:71
  58: trash::remove<str*>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.1\src\lib.rs:49
  59: TESTING::main::{{closure}}
             at .\src\main.rs:28
  60: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:200
  61: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc\boxed.rs:1024
  62: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:239
  63: std::panic::{{impl}}::call_once<(),closure-0>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:318
  64: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:303
  65: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  66: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  67: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  68: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),(),closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  69: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:233
  70: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_new_events<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:360
  71: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::move_state_to<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:296
  72: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::poll<()>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:199
  73: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:209
  74: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:185
  75: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\Users\u\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\event_loop.rs:149
  76: TESTING::main
             at .\src\main.rs:17
  77: std::rt::lang_start::{{closure}}<()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\rt.rs:67
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\rt.rs:52
  79: std::panicking::try::do_call<closure-0,i32>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:303
  80: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  81: std::panicking::try
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:281
  82: std::panic::catch_unwind
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panic.rs:394
  83: std::rt::lang_start_internal
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\rt.rs:51
  84: std::rt::lang_start<()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\rt.rs:67
  85: main
  86: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  87: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panic.rs:394
  83: std::rt::lang_start_internal
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\rt.rs:51
  84: std::rt::lang_start<()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\rt.rs:67
  85: main
  86: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  87: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  88: BaseThreadInitThunk
  89: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by hecrj** [comment]
@nnt0 Yes, either `winit` or `trash`. Hard to say which one is at fault without more investigation!

**Comment by nnt0** [comment]
Okay, thank you!

**Comment by VZout** [comment]
I'm having a similar issue with `msgbox` which just creates a messagebox with the Winapi:
```
pub fn create(title: &str, content: &str, icon_type: IconType) {
    use std::iter::once;
    use std::ptr::null_mut;
    use winapi::um::winuser::{
        MessageBoxW, MB_ICONERROR, MB_ICONINFORMATION, MB_OK, MB_SYSTEMMODAL,
    };

    let lp_text: Vec<u16> = content.encode_utf16().chain(once(0)).collect();
    let lp_caption: Vec<u16> = title.encode_utf16().chain(once(0)).collect();

    let window_type = match icon_type {
        IconType::Error => MB_OK | MB_ICONERROR | MB_SYSTEMMODAL,
        IconType::Info => MB_OK | MB_ICONINFORMATION | MB_SYSTEMMODAL,
        IconType::None => MB_OK | MB_SYSTEMMODAL,
    };

    unsafe {
        MessageBoxW(
            null_mut(),
            lp_text.as_ptr(),
            lp_caption.as_ptr(),
            window_type,
        );
    }
}

```
