### ISSUE TITLE
Example panic (driver dependency?)

### ISSUE THREAD

**Issue by cGuille** [hecrj/iced#422]
Hello,

I would like to build a GUI in Rust for a learning project. After reading the README I found iced quite appealing, but I don't seem to be able to run the examples on my machine.

My issue seems to be somewhat related to #69, #263 or #284. I was not sure about creating a new one but I think it will be easier like that; just tell me if you would rather keep the discussion in another one.

What I did:
- Clone the repository.
- Run `cargo test` → all green.
- Run `cargo run --package color_palette`.

At this point, I got this panic:
```
thread 'main' panicked at 'Could not find a suitable graphics adapter', wgpu/src/window/compositor.rs:68:26
```

I searched the issues and figured out that I may have to install Vulkan drivers. I installed the Ubuntu package `mesa-vulkan-drivers` and ran the example again. Now I have the following error:
```
INTEL-MESA: warning: Haswell Vulkan support is incomplete
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
thread 'main' panicked at 'Surface Surface doesn't support queue family QueueFamily { properties: QueueFamilyProperties { queue_flags: GRAPHICS | COMPUTE | TRANSFER, queue_count: 1, timestamp_valid_bits: 36, min_image_transfer_granularity: Extent3D { width: 1, height: 1, depth: 1 } }, device: 0x55f1fb3b0520, index: 0 }', /home/gcharmetant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With `RUST_BACKTRACE=full`:
<details>
<summary>show / hide</summary>

```
INTEL-MESA: warning: Haswell Vulkan support is incomplete
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
thread 'main' panicked at 'Surface Surface doesn't support queue family QueueFamily { properties: QueueFamilyProperties { queue_flags: GRAPHICS | COMPUTE | TRANSFER, queue_count: 1, timestamp_valid_bits: 36, min_image_transfer_granularity: Extent3D { width: 1, height: 1, depth: 1 } }, device: 0x56108831a590, index: 0 }', /home/gcharmetant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x561087b46784 - backtrace::backtrace::libunwind::trace::h812748238d609e46
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x561087b46784 - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x561087b46784 - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x561087b46784 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x561087b6df7c - core::fmt::write::h543cdf60775f89bf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x561087b435d3 - std::io::Write::write_fmt::h0c7f3ce24c679426
                               at src/libstd/io/mod.rs:1504
   6:     0x561087b48fb5 - std::sys_common::backtrace::_print::h80e55e24be231368
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x561087b48fb5 - std::sys_common::backtrace::print::h3b197b9c1261c865
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x561087b48fb5 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
                               at src/libstd/panicking.rs:198
   9:     0x561087b48cf2 - std::panicking::default_hook::he49a9c12e358cc45
                               at src/libstd/panicking.rs:218
  10:     0x561087b49612 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:511
  11:     0x561087b491fb - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x561087b4916b - std::panicking::begin_panic_fmt::hfa6ef29ba81f400e
                               at src/libstd/panicking.rs:373
  13:     0x5610872e290a - wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_swap_chain::hb4a01f030e0f27d7
                               at /home/gcharmetant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16
  14:     0x5610872be2ad - wgpu_device_create_swap_chain
                               at /home/gcharmetant/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.5.0/src/device.rs:356
  15:     0x561087183a0f - wgpu::Device::create_swap_chain::hfa37dc9f0f9c28db
                               at /home/gcharmetant/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.5.0/src/lib.rs:1005
  16:     0x5610870add46 - <iced_wgpu::window::compositor::Compositor as iced_graphics::window::compositor::Compositor>::create_swap_chain::ha5bf663e6653f61c
                               at wgpu/src/window/compositor.rs:89
  17:     0x561087066c83 - iced_winit::application::run::h7d596892ffa7f143
                               at /home/gcharmetant/projects/cGuille/rustgui/iced/winit/src/application.rs:166
  18:     0x561086f93544 - iced::application::Application::run::h610637098dac24b9
                               at /home/gcharmetant/projects/cGuille/rustgui/iced/src/application.rs:229
  19:     0x561086f937c1 - iced::sandbox::Sandbox::run::h452b822ea6ce2798
                               at /home/gcharmetant/projects/cGuille/rustgui/iced/src/sandbox.rs:166
  20:     0x56108702b66d - color_palette::main::hd65359e2f6aa8c8d
                               at examples/color_palette/src/main.rs:12
  21:     0x561086f741bb - std::rt::lang_start::{{closure}}::h5a971dc740c90ffc
                               at /home/gcharmetant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  22:     0x561087b49b28 - std::rt::lang_start_internal::{{closure}}::h44dc84346eeba462
                               at src/libstd/rt.rs:52
  23:     0x561087b49b28 - std::panicking::try::do_call::h3559ee6be71549e2
                               at src/libstd/panicking.rs:331
  24:     0x561087b49b28 - std::panicking::try::h78f4c77016541848
                               at src/libstd/panicking.rs:274
  25:     0x561087b49b28 - std::panic::catch_unwind::hfe46f382761b3d41
                               at src/libstd/panic.rs:394
  26:     0x561087b49b28 - std::rt::lang_start_internal::he05790f0cb2000df
                               at src/libstd/rt.rs:51
  27:     0x561086f74197 - std::rt::lang_start::h851d21d8f27b15a6
                               at /home/gcharmetant/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  28:     0x56108702d4fa - main
  29:     0x7fb05b754830 - __libc_start_main
  30:     0x561086f65369 - _start
  31:                0x0 - <unknown>
```

</details>

So, follow up questions:

- Does anybody know what I am still missing? I am almost 100% noob about GUI development and do not know the way forward.
- As far as I can understand, iced has some runtime requirements that are not obvious. Is there some part of the documentation where this is explained? Should there be a link in the README about this?
- If I were to package an executable using iced, what dependencies should I specify or bundle with my binary? Is it explained somewhere?

Have a nice day!

Guillaume.

**Comment by hecrj** [comment]
> I searched the issues and figured out that I may have to install Vulkan drivers.

You could try switching to OpenGL rendering. This can be achieved by enabling the `glow` feature.

> - As far as I can understand, iced has some runtime requirements that are not obvious. Is there some part of the documentation where this is explained? Should there be a link in the README about this?
> - If I were to package an executable using iced, what dependencies should I specify or bundle with my binary? Is it explained somewhere?

There is some discussion about this in #256 and #210.

**Comment by cGuille** [comment]
Thanks for the heads up!

I have been trying to run some examples with the `--features glow`; is that what I am supposed to do?

If it is, I have encountered some compile-time errors. For instance, if I run `cargo run --features glow --package color_palette`, I get:
```
error[E0432]: unresolved import `crate::renderer::widget::canvas`
  --> src/widget.rs:31:13
   |
31 |     pub use crate::renderer::widget::canvas;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `canvas` in `widget`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `iced`.

To learn more, run the command again with --verbose.
```

And if I run `cargo run --features glow --package tour`:
```
error[E0277]: the trait bound `iced_glow::backend::Backend: iced_graphics::backend::Image` is not satisfied
   --> examples/tour/src/main.rs:675:5
    |
675 |     Container::new(
    |     ^^^^^^^^^^^^^^ the trait `iced_graphics::backend::Image` is not implemented for `iced_glow::backend::Backend`
    |
    = note: required because of the requirements on the impl of `iced_native::widget::image::Renderer` for `iced_graphics::renderer::Renderer<iced_glow::backend::Backend>`
    = note: required because of the requirements on the impl of `std::convert::From<iced_native::widget::image::Image>` for `iced_native::element::Element<'_, _, iced_graphics::renderer::Renderer<iced_glow::backend::Backend>>`
    = note: required because of the requirements on the impl of `std::convert::Into<iced_native::element::Element<'_, _, iced_graphics::renderer::Renderer<iced_glow::backend::Backend>>>` for `iced_native::widget::image::Image`
    = note: required by `iced_native::widget::container::Container::<'a, Message, Renderer>::new`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `tour`.

To learn more, run the command again with --verbose.
```

I think I will stop there; maybe this project is too early for newcomers like me and I don't want to waste your time.

**Comment by hecrj** [comment]
> unresolved import `crate::renderer::widget::canvas`

Because of the way `cargo` features work currently, you need to enable the `glow_canvas` separately too.

> the trait bound `iced_glow::backend::Backend: iced_graphics::backend::Image` is not satisfied

`iced_glow` does not support `Image` and `Svg` widgets yet. You can find more details in #354.

**Comment by cGuille** [comment]
That does the trick!

With the following command, I have been able to build most of the examples:

```bash
cargo build --features glow,glow_canvas --package "$example"
```

Only the `pokedex`, `svg`, and `tour` examples do not compile because of the limitations you mentioned.

All the other examples ran successfully except the `integration` which panicked at 'Request adapter' (examples/integration/src/main.rs:34:23).

At this point I can start trying to build something myself.
Thank you very much!
