### ISSUE TITLE
examples crash on start on macOS Big Sur

### ISSUE THREAD

**Issue by sassman** [hecrj/iced#633]
Hi,

I have no luck in getting the examples run. So far I've tried: stopwatch, tour, todos. All fail. I tried on master @ 87c9df294c79d73ff67a8d9a036cf9ddff24c52f and on tag native-0.2.2.

most issues seems to be rooted at `'attempted to leave type `linked_hash_map::Node<u32, glyph_brush_draw_cache::Row>` uninitialized, which is invalid'`

### `RUST_BACKTRACE=full cargo run --package tour`
<details>
  <summary>tour trace</summary>

```plain
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `target/debug/tour`
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<u32, glyph_brush_draw_cache::Row>` uninitialized, which is invalid', /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0:        0x10966c5f4 - std::backtrace_rs::backtrace::libunwind::trace::h6df1416181381e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:        0x10966c5f4 - std::backtrace_rs::backtrace::trace_unsynchronized::h792524067a83cded
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:        0x10966c5f4 - std::sys_common::backtrace::_print_fmt::he614892186429f3f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:        0x10966c5f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:        0x109689fa0 - core::fmt::write::haf3903118f694c48
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:        0x1096695a6 - std::io::Write::write_fmt::h7385463ac87804ed
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:        0x10966e24f - std::sys_common::backtrace::_print::ha64a9740ea6183e6
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:        0x10966e24f - std::sys_common::backtrace::print::h1fad353b070e1eef
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:        0x10966e24f - std::panicking::default_hook::{{closure}}::h91bd4c58cf71392b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:        0x10966df1d - std::panicking::default_hook::h7bd29c87df967048
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:        0x10966e81b - std::panicking::rust_panic_with_hook::hae2b05f08a320721
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:        0x10966e39b - std::panicking::begin_panic_handler::{{closure}}::h72d68d3a77e0b718
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:        0x10966ca68 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c5e286792f94edb
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:        0x10966e35a - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:        0x1096a2bbf - core::panicking::panic_fmt::h1b194bb80d76fb10
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:        0x1096a2b17 - core::panicking::panic::hdb9dddaff64fd68b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:        0x1088a39d7 - core::mem::uninitialized::ha34eca8951245498
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658
  17:        0x1088a39d7 - linked_hash_map::LinkedHashMap<K,V,S>::ensure_guard_node::hefe65524f1b2a323
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174
  18:        0x1088a3ccc - linked_hash_map::LinkedHashMap<K,V,S>::insert::h8e36d6ba41665bcb
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:304
  19:        0x1088bdc2c - glyph_brush_draw_cache::DrawCache::cache_queued::h5a5979fab0133306
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/glyph_brush_draw_cache-0.1.3/src/lib.rs:767
  20:        0x1088a1330 - glyph_brush::glyph_brush::GlyphBrush<V,X,F,H>::process_queued::hb4d2f6838662e767
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/glyph_brush-0.7.0/src/glyph_brush.rs:498
  21:        0x108849573 - iced_wgpu::text::Pipeline::trim_measurement_cache::h07f2710a8a280997
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/wgpu/src/text.rs:124
  22:        0x108845298 - <iced_wgpu::backend::Backend as iced_graphics::backend::Backend>::trim_measurements::h65f749f0b156f5b7
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/wgpu/src/backend.rs:251
  23:        0x108642e95 - <iced_graphics::renderer::Renderer<B> as iced_native::renderer::Renderer>::layout::h68e781ea7c96616b
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/graphics/src/renderer.rs:54
  24:        0x10867e7ba - iced_native::user_interface::UserInterface<Message,Renderer>::build::h0f5337e7576cd206
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/native/src/user_interface.rs:115
  25:        0x1085fe5cd - iced_winit::application::build_user_interface::h6b050fca083a0c4a
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/winit/src/application.rs:427
  26:        0x1085fc3ac - iced_winit::application::run_instance::{{closure}}::h335c665149267102
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/winit/src/application.rs:232
  27:        0x10867d650 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3c2464db6f94cb00
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  28:        0x1085ff6b2 - iced_winit::application::run::{{closure}}::h62233e783bf1e012
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/winit/src/application.rs:191
  29:        0x1085de2d7 - <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut::h37d52918b2ab51ca
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1049
  30:        0x108676543 - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::h5aa8d33746325a66
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/app_state.rs:71
  31:        0x10956cea0 - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::hcd9641b50cb7a39f
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/app_state.rs:173
  32:        0x10956d806 - winit::platform_impl::platform::app_state::AppState::launched::hb66becf81f30b78e
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/app_state.rs:262
  33:        0x1095894f1 - winit::platform_impl::platform::app_delegate::did_finish_launching::h977581ea62863ac5
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/app_delegate.rs:63
  34:     0x7fff2042dfdc - <unknown>
  35:     0x7fff204c989b - <unknown>
  36:     0x7fff204c980f - <unknown>
  37:     0x7fff203febce - <unknown>
  38:     0x7fff2116aabe - <unknown>
  39:     0x7fff22c590f1 - <unknown>
  40:     0x7fff22c58e3f - <unknown>
  41:     0x7fff22c5603a - <unknown>
  42:     0x7fff22c55c90 - <unknown>
  43:     0x7fff21196056 - <unknown>
  44:     0x7fff21195ec6 - <unknown>
  45:     0x7fff262000b9 - <unknown>
  46:     0x7fff261ff7d4 - <unknown>
  47:     0x7fff261f8440 - <unknown>
  48:     0x7fff286b4f12 - <unknown>
  49:     0x7fff22c50412 - <unknown>
  50:     0x7fff22c4e74b - <unknown>
  51:     0x7fff22c40bda - <unknown>
  52:        0x1095ac836 - <() as objc::message::MessageArguments>::invoke::h9a02f106afd21caa
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  53:        0x1095ab5dd - objc::message::platform::send_unverified::h2fea7448e5b4ed8a
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  54:        0x108671e0e - objc::message::send_message::h083530ab5ff1e46b
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  55:        0x108671e0e - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::h04a01b9b54a8eff6
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/event_loop.rs:106
  56:        0x108673064 - winit::platform_impl::platform::event_loop::EventLoop<T>::run::h7dfacad48f2a251e
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/event_loop.rs:93
  57:        0x10866d590 - winit::event_loop::EventLoop<T>::run::h06106578af78f40e
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/event_loop.rs:154
  58:        0x1085ff2a4 - iced_winit::application::run::h857e5570abf73783
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/winit/src/application.rs:181
  59:        0x108637431 - iced::application::Application::run::hd67063e9258beb32
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/src/application.rs:229
  60:        0x108637818 - iced::sandbox::Sandbox::run::h29636d855b073c3f
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/src/sandbox.rs:166
  61:        0x108628bfe - tour::main::h3c7b7c808563a126
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/examples/tour/src/main.rs:10
  62:        0x1086072c5 - core::ops::function::FnOnce::call_once::h48bfd8a36d712d69
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  63:        0x1085f4fac - std::sys_common::backtrace::__rust_begin_short_backtrace::h85d038033fe8e7ee
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  64:        0x1085d0a18 - std::rt::lang_start::{{closure}}::ha626171bdf3b0828
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66
  65:        0x10966ec74 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4daab3ed47411afb
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  66:        0x10966ec74 - std::panicking::try::do_call::h5f7f7b1d8bd7dc86
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  67:        0x10966ec74 - std::panicking::try::h29495f6475fc1ef1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  68:        0x10966ec74 - std::panic::catch_unwind::h1ebce9249c33ec53
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  69:        0x10966ec74 - std::rt::lang_start_internal::hd38bb63f9540b327
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  70:        0x1085d09f1 - std::rt::lang_start::h10816a4dc16c1fd2
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65
  71:        0x10862e8c2 - _main
[2020-11-25T08:56:17Z ERROR gfx_memory::heaps] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 54771712, effective: 30123776 }, size: 18446744073709551615 }
[2020-11-25T08:56:17Z ERROR gfx_memory::heaps] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 16777216, effective: 1280 }, size: 1073741824 }
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(256) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(2048) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(16384) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(4194304) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(1048576) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(25600) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(2600192) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(5600000) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(1400064) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(12800) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(240128) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(60160) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(40192) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(36096) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(16814080) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::general] Memory leak: SizeEntry(4206592) is still used
[2020-11-25T08:56:17Z ERROR gfx_memory::allocator::linear] Not all allocations from LinearAllocator were freed
[2020-11-25T08:56:17Z ERROR gfx_descriptor::allocator] DescriptorAllocator is dropped
[2020-11-25T08:56:17Z ERROR gfx_backend_metal::command] Command buffer not released properly!
```

</details>

### `RUST_BACKTRACE=full cargo run --package todos`
<details>
  <summary>todos trace</summary>

```plain
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/todos`
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<u32, glyph_brush_draw_cache::Row>` uninitialized, which is invalid', /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0:        0x10fd277a4 - std::backtrace_rs::backtrace::libunwind::trace::h6df1416181381e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:        0x10fd277a4 - std::backtrace_rs::backtrace::trace_unsynchronized::h792524067a83cded
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:        0x10fd277a4 - std::sys_common::backtrace::_print_fmt::he614892186429f3f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:        0x10fd277a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:        0x10fd45120 - core::fmt::write::haf3903118f694c48
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:        0x10fd24ea6 - std::io::Write::write_fmt::h7385463ac87804ed
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:        0x10fd293ff - std::sys_common::backtrace::_print::ha64a9740ea6183e6
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:        0x10fd293ff - std::sys_common::backtrace::print::h1fad353b070e1eef
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:        0x10fd293ff - std::panicking::default_hook::{{closure}}::h91bd4c58cf71392b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:        0x10fd290cd - std::panicking::default_hook::h7bd29c87df967048
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:        0x10fd299cb - std::panicking::rust_panic_with_hook::hae2b05f08a320721
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:        0x10fd2954b - std::panicking::begin_panic_handler::{{closure}}::h72d68d3a77e0b718
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:        0x10fd27c18 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c5e286792f94edb
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:        0x10fd2950a - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:        0x10fd5c16f - core::panicking::panic_fmt::h1b194bb80d76fb10
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:        0x10fd5c0c7 - core::panicking::panic::hdb9dddaff64fd68b
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:        0x10f1c16c7 - core::mem::uninitialized::hbae12d2b4bb1568a
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658
  17:        0x10f1c16c7 - linked_hash_map::LinkedHashMap<K,V,S>::ensure_guard_node::h7254d14235272a7c
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174
  18:        0x10f1c19bc - linked_hash_map::LinkedHashMap<K,V,S>::insert::hf6822a5d8ce6e9c9
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:304
  19:        0x10f1adbfc - glyph_brush_draw_cache::DrawCache::cache_queued::ha9939e9206987fe9
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/glyph_brush_draw_cache-0.1.3/src/lib.rs:767
  20:        0x10f1ddca0 - glyph_brush::glyph_brush::GlyphBrush<V,X,F,H>::process_queued::hebca3336f0e96d81
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/glyph_brush-0.7.0/src/glyph_brush.rs:498
  21:        0x10f2130e3 - iced_wgpu::text::Pipeline::trim_measurement_cache::h8a1eb71a6f54e4ae
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/wgpu/src/text.rs:124
  22:        0x10f261348 - <iced_wgpu::backend::Backend as iced_graphics::backend::Backend>::trim_measurements::hb52a73848b73b36e
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/wgpu/src/backend.rs:251
  23:        0x10f0b3d85 - <iced_graphics::renderer::Renderer<B> as iced_native::renderer::Renderer>::layout::ha104fd6d3f49f443
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/graphics/src/renderer.rs:54
  24:        0x10f0e649a - iced_native::user_interface::UserInterface<Message,Renderer>::build::hecd0f2e67cb83eb7
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/native/src/user_interface.rs:115
  25:        0x10f10b7bd - iced_winit::application::build_user_interface::h555362cec94af249
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/winit/src/application.rs:427
  26:        0x10f1095d3 - iced_winit::application::run_instance::{{closure}}::hdfa9a44b235d5ea4
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/winit/src/application.rs:232
  27:        0x10f182960 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf029a7c7b0f48564
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  28:        0x10f10c852 - iced_winit::application::run::{{closure}}::hbe02694570a7ff00
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/winit/src/application.rs:191
  29:        0x10f15f457 - <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut::hae0f6133f4c982f4
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1049
  30:        0x10f0d2413 - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::h06c5c16441e747c8
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/app_state.rs:71
  31:        0x10fbbb160 - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::heb42cc82758ab40f
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/app_state.rs:173
  32:        0x10fbbbac6 - winit::platform_impl::platform::app_state::AppState::launched::hcd7f895797a40017
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/app_state.rs:262
  33:        0x10fbd7e21 - winit::platform_impl::platform::app_delegate::did_finish_launching::hbc84a971b290ba32
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/app_delegate.rs:63
  34:     0x7fff2042dfdc - <unknown>
  35:     0x7fff204c989b - <unknown>
  36:     0x7fff204c980f - <unknown>
  37:     0x7fff203febce - <unknown>
  38:     0x7fff2116aabe - <unknown>
  39:     0x7fff22c590f1 - <unknown>
  40:     0x7fff22c58e3f - <unknown>
  41:     0x7fff22c5603a - <unknown>
  42:     0x7fff22c55c90 - <unknown>
  43:     0x7fff21196056 - <unknown>
  44:     0x7fff21195ec6 - <unknown>
  45:     0x7fff262000b9 - <unknown>
  46:     0x7fff261ff7d4 - <unknown>
  47:     0x7fff261f8440 - <unknown>
  48:     0x7fff286b4f12 - <unknown>
  49:     0x7fff22c50412 - <unknown>
  50:     0x7fff22c4e74b - <unknown>
  51:     0x7fff22c40bda - <unknown>
  52:        0x10fbfb6d6 - <() as objc::message::MessageArguments>::invoke::h9a02f106afd21caa
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  53:        0x10fbfa47d - objc::message::platform::send_unverified::h2fea7448e5b4ed8a
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  54:        0x10f16079e - objc::message::send_message::heac8fa79e6ca5883
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  55:        0x10f16079e - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::h09f3ffbea62dab80
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/event_loop.rs:106
  56:        0x10f1619f4 - winit::platform_impl::platform::event_loop::EventLoop<T>::run::h43c8f379d0362ab9
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/macos/event_loop.rs:93
  57:        0x10f0e78b0 - winit::event_loop::EventLoop<T>::run::h3097a71f8bfb34da
                               at /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/event_loop.rs:154
  58:        0x10f10c43e - iced_winit::application::run::h23cc8e3ee5049196
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/winit/src/application.rs:181
  59:        0x10f134821 - iced::application::Application::run::h0f48ab0c3aa86c5a
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/src/application.rs:229
  60:        0x10f0cae9c - todos::main::hed47e640cb30ae63
                               at /Users/d34dl0ck/workspaces/rust/gui/iced/examples/todos/src/main.rs:9
  61:        0x10f13af35 - core::ops::function::FnOnce::call_once::hd9242252a6d7afd7
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  62:        0x10f0bacac - std::sys_common::backtrace::__rust_begin_short_backtrace::h75ac95cbf2141d2a
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  63:        0x10f177c68 - std::rt::lang_start::{{closure}}::hc63b50aaf17e543d
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66
  64:        0x10fd29e24 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4daab3ed47411afb
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  65:        0x10fd29e24 - std::panicking::try::do_call::h5f7f7b1d8bd7dc86
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  66:        0x10fd29e24 - std::panicking::try::h29495f6475fc1ef1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  67:        0x10fd29e24 - std::panic::catch_unwind::h1ebce9249c33ec53
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  68:        0x10fd29e24 - std::rt::lang_start_internal::hd38bb63f9540b327
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  69:        0x10f177c41 - std::rt::lang_start::h02a401a501a20f88
                               at /Users/d34dl0ck/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65
  70:        0x10f0cf532 - _main
```
</details>

### Versions
- macOS 11.0.1 (20B29)
- rustc 1.48.0 (7eac88abb 2020-11-16)
- cargo 1.48.0 (65cbdd2dc 2020-10-14)

**Comment by sassman** [comment]
FYI: I went to `https://github.com/alexheretic/glyph-brush` and run their examples like `cargo run -p glyph_brush --example opengl --release` and that went successful.

**Comment by myfreeweb** [comment]
Huh, this looks oddly familiar.

> attempted to leave type `linked_hash_map::Node<u32, glyph_brush_draw_cache::Row>` uninitialized, which is invalid

I've hit this in Firefox: https://github.com/rust-lang/rust/issues/77585 tl;dr old `linked_hash_map` version + new rustc.

Do a `cargo update`?

**Comment by sassman** [comment]
Wow, `cargo update` and then re-run the examples fixed it.

So maybe it is really worth to commit the `Cargo.lock` file as well, at least for the examples it would actually makes a lot of sense then.

Thanks for the help.

**Comment by hecrj** [comment]
If I clone the repository from scratch and run `cargo --package tour` and then `cargo update`, my `Cargo.lock` doesn't change at all between these commands.

@myfreeweb @sassman I imagine this is different for you? Could this be a cargo bug? What is exactly changing?

**Comment by sassman** [comment]
> On the other hand, if you already have the repository cloned and you are pulling changes after a while... Then, I imagine you could have outdated dependencies which could cause issues.

That was exactly my case. Did the clone ages ago, then only fetch & pull and of course I totally forgot about the Cargo.lock that got created when executing the examples the last time.

**Comment by hecrj** [comment]
I would be fine with versioning the `Cargo.lock` of all the examples, but I am not sure if that's possible in a cargo workspace. AFAIK, everything shares the same lockfile in the root directory.

**Comment by sassman** [comment]
> I guess we could create a different workspace for all the examples... I will think about it!

Hm, not sure if sub-workspaces are supported, but if so that might solve it yes.

**Comment by myfreeweb** [comment]
Yes, everything shares the same lockfile in the root directory, but I don't see how this is a problem. [Your favorite FAQ entry](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) doesn't say `Cargo.lock` is *harmful* for libraries, just that it's *unused* by external library consumers, which is like, okay, you just have to know that :)

**Comment by hecrj** [comment]
@myfreeweb I am just trying to understand the issue.

If we decide to go against [the guide recommendation](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) and version the `Cargo.lock` file, at least I'd like to know why.

In particular, I don't believe we should maintain the lockfile just because users can forget to run `cargo update` every once in a while. So far, I suspect this is what is happening.

Is there any well-known library that versions the `Cargo.lock` file?
