### ISSUE TITLE
Build script panic when building dependency "x11"

### ISSUE THREAD

**Issue by zack-emmert** [hecrj/iced#75]
When attempting to build `iced` the custom build script for `x11` panics, however, when cloning `x11` from source directly and attempting to build it, it built without issue. I've included the stacktrace below:
```
error: failed to run custom build command for `x11 v2.18.1`

Caused by:
  process didn't exit successfully: `/home/zack/CLionProjects/Rust/iced_testing/target/debug/build/x11-78cf3bc4c321325c/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"x11\" \"x11 >= 1.4.99.1\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package x11 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `x11.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'x11\', required by \'virtual:world\', not found\nPackage \'x11\', required by \'virtual:world\', not found\n" } }', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55ae9bdbe2e4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55ae9bdbe2e4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55ae9bdbe2e4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55ae9bdbe2e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55ae9bddc7dc - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55ae9bdbb627 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55ae9bdc07a5 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55ae9bdc07a5 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55ae9bdc07a5 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55ae9bdc0496 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55ae9bdc0df5 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55ae9bdc0992 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55ae9bdc0886 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55ae9bdd9eea - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55ae9bdd9fe7 - core::result::unwrap_failed::ha8b77e6004f0ba38
                               at src/libcore/result.rs:1165
  15:     0x55ae9bd7a747 - core::result::Result<T,E>::unwrap::h4e34b216e65974e2
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:933
  16:     0x55ae9bd79e22 - build_script_build::main::h11f4fc9c02b5d0ff
                               at /home/zack/.cargo/registry/src/github.com-1ecc6299db9ec823/x11-2.18.1/build.rs:36
  17:     0x55ae9bd7c320 - std::rt::lang_start::{{closure}}::h6bfd41807862563b
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  18:     0x55ae9bdc0873 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  19:     0x55ae9bdc0873 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  20:     0x55ae9bdc6dfa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  21:     0x55ae9bdc12ed - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  22:     0x55ae9bdc12ed - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  23:     0x55ae9bdc12ed - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  24:     0x55ae9bd7c2f9 - std::rt::lang_start::hc65c0d8d6217d1a5
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  25:     0x55ae9bd79f1a - main
  26:     0x7f1376ece1a3 - __libc_start_main
  27:     0x55ae9bd791fe - _start
  28:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
```
This is occurring on a fully updated installation of Fedora 31 with KDE (so Xorg is installed).

**Comment by Friz64** [comment]
Are you sure you have the development files for x11 installed?

**Comment by zack-emmert** [comment]
I didn't have the package installed, but installing it didn't fix the issue either.

**Comment by zack-emmert** [comment]
Turns out the packages I was missing was `libX11-devel`, `freetype-devel`, and `expat-devel`. It builds correctly now.

**Comment by hecrj** [comment]
This may have been related to the build issues in #58. Do you have `pkg-config` installed? It can help to avoid compiling dependencies.
