### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by oOBoomberOo** [hecrj/iced#79]
This error popup on every example project and even on my own iced project.
```
thread 'main' panicked at 'Unable to enumerate instance extensions: ERROR_INITIALIZATION_FAILED', src\libcore\result.rs:1189:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Also, when I try to import module in VS code it doesn't seem to provide import suggestion for component (i.e. `iced::button`, `iced::Element`) but it does provide import to `settings`, `Sandbox` and `Settings`

System:
OS: Windows 10
GPU: Nvidia GeForce GTX 1080 (Up to date driver)
Version: `iced = 0.1.0-beta`
Rust: stable-x86_64-pc-windows-msvc

**Comment by incubus8** [comment]
Got similar error with MacOS pulled from latest `master` branch. 

Here is the stacktrace:

```
➜ RUST_BACKTRACE=1 cargo run --example todos
   Compiling iced v0.1.0-beta (/iced)
    Finished dev [unoptimized + debuginfo] target(s) in 11.70s
     Running `/iced/target/debug/examples/todos`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Compiler encountered an internal error"', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libcore/result.rs:933
  16: gfx_backend_metal::internal::ServicePipes::create_copy_buffer
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.4.1/src/internal.rs:496
  17: gfx_backend_metal::internal::ServicePipes::new
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.4.1/src/internal.rs:461
  18: gfx_backend_metal::Shared::new
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.4.1/src/lib.rs:191
  19: <gfx_backend_metal::Instance as gfx_hal::Instance<gfx_backend_metal::Backend>>::enumerate_adapters::{{closure}}
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.4.1/src/lib.rs:229
  20: core::iter::adapters::map_fold::{{closure}}
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libcore/iter/adapters/mod.rs:694
  21: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libcore/iter/traits/iterator.rs:1828
  22: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libcore/iter/traits/iterator.rs:1709
  23: core::iter::traits::iterator::Iterator::fold
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libcore/iter/traits/iterator.rs:1831
  24: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libcore/iter/adapters/mod.rs:727
  25: core::iter::traits::iterator::Iterator::for_each
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libcore/iter/traits/iterator.rs:631
  26: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/liballoc/vec.rs:2031
  27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/liballoc/vec.rs:2014
  28: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/liballoc/vec.rs:1901
  29: core::iter::traits::iterator::Iterator::collect
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libcore/iter/traits/iterator.rs:1493
  30: <gfx_backend_metal::Instance as gfx_hal::Instance<gfx_backend_metal::Backend>>::enumerate_adapters
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.4.1/src/lib.rs:225
  31: wgpu_native::instance::request_adapter
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.0/src/instance.rs:347
  32: wgpu_request_adapter
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.0/src/instance.rs:474
  33: wgpu::Adapter::request
             at /.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  34: iced_wgpu::renderer::Renderer::new
             at wgpu/src/renderer.rs:51
  35: <iced_wgpu::renderer::Renderer as iced_native::renderer::windowed::Windowed>::new
             at wgpu/src/renderer.rs:417
  36: iced_winit::application::Application::run
             at /iced/winit/src/application.rs:115
  37: iced::application::Application::run
             at /iced/src/application.rs:140
  38: todos::main
             at examples/todos.rs:9
  39: std::rt::lang_start::{{closure}}
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libstd/rt.rs:61
  40: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  41: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  42: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:83
  43: std::panicking::try
             at src/libstd/panicking.rs:265
  44: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  45: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  46: std::rt::lang_start
             at /rustc/c553e8e8812c19809e70523064989e66c5cfd3f1/src/libstd/rt.rs:61
  47: <todos::SaveError as core::clone::Clone>::clone
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by hecrj** [comment]
Thank you for reporting!

Just to discard an issue upstream, I'd appreciate it if you could try any of the examples in [`wgpu`] and see if the same issue happens.

[`wgpu`]: https://github.com/gfx-rs/wgpu-rs

**Comment by oOBoomberOo** [comment]
Tested, seem to be wgpu problem.
It displays the exact same error.

**Comment by oOBoomberOo** [comment]
Actually, after following down the rabbit hole. The problem seem to come from the Vulkan itself.
I'll try updating the graphics driver and see if the problem go away.

**Comment by FuGangqiang** [comment]
I also got this error, The problem seem to come from the Vulkan itself,
[archlinux wiki](https://wiki.archlinux.org/index.php/Vulkan#Nvidia_-_vulkan_is_not_working_and_can_not_initialize) has some doc

**Comment by oOBoomberOo** [comment]
The issue is fixed after reinstalling graphic driver.
