### ISSUE TITLE
Window closes when resized (Linux)

### ISSUE THREAD

**Issue by RsPlayer** [hecrj/iced#87]
![2019-11-29 17-29-36](https://user-images.githubusercontent.com/49613045/69881719-25811180-12ce-11ea-9cf6-8a14f70f2726.gif)

When I try to resize window it suddenly closes. this happens only with `debug` mode but in release mode it resizes without problem.

OS: Fedora 31 KDE Plasma
Display manager: Xorg

log With `RUST_BACKTRACE=1`
```
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 32767', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2717:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  15: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2717
  16: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2568
  17: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/vec.rs:1796
  18: <gfx_backend_vulkan::window::Surface as gfx_hal::window::PresentationSurface<gfx_backend_vulkan::Backend>>::acquire_image
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.4.0/src/window.rs:507
  19: wgpu_native::swap_chain::swap_chain_get_next_texture
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.1/src/swap_chain.rs:156
  20: wgpu_swap_chain_get_next_texture
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.1/src/swap_chain.rs:214
  21: wgpu::SwapChain::get_next_texture
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1355
  22: iced_wgpu::renderer::target::Target::next_frame
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.1.0/src/renderer/target.rs:30
  23: iced_wgpu::renderer::Renderer::draw
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.1.0/src/renderer.rs:88
  24: <iced_wgpu::renderer::Renderer as iced_native::renderer::windowed::Windowed>::draw
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.1.0/src/renderer.rs:426
  25: iced_winit::application::Application::run::{{closure}}
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0-alpha/src/application.rs:229
  26: winit::platform_impl::platform::sticky_exit_callback
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:693
  27: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:305
  28: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/x11/mod.rs:389
  29: winit::platform_impl::platform::EventLoop<T>::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/platform_impl/linux/mod.rs:640
  30: winit::event_loop::EventLoop<T>::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha4/src/event_loop.rs:148
  31: iced_winit::application::Application::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0-alpha/src/application.rs:144
  32: iced::application::Application::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.0-beta/src/application.rs:140
  33: iced::sandbox::Sandbox::run
             at /home/master/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.0-beta/src/sandbox.rs:128
  34: iced_test::main
             at src/main.rs:4
  35: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  36: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  37: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  38: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  39: std::panicking::try
             at src/libstd/panicking.rs:271
  40: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  41: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  42: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  43: main
  44: __libc_start_main
  45: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by hecrj** [comment]
This may be [`wgpu`] not being able to keep up with the resizes in `debug` mode. Could you try the examples there and see if they have the same issue?

[`wgpu`]: https://github.com/gfx-rs/wgpu-rs

**Comment by RsPlayer** [comment]
same issue for other examples too

**Comment by RsPlayer** [comment]
![2019-11-3010-41-21](https://user-images.githubusercontent.com/49613045/69898791-34170980-135e-11ea-8e37-093d4508bf9c.gif)

**Comment by RsPlayer** [comment]
You're right, the problem is from wgpu.
![2019-11-3011-08-19](https://user-images.githubusercontent.com/49613045/69899133-590d7b80-1362-11ea-9461-2d477a897899.gif)
I posted a new issue in their repo
https://github.com/gfx-rs/wgpu-rs/issues/136#issue-530560059
